#Created by BGHDDevelopment(Noodles)
#Discord/Support: https://bghddevelopment.com/discord
#Plugin Link: https://www.spigotmc.org/resources/52072/
#Website: https://bghddevelopment.com
#Wiki: https://wiki.bghddevelopment.com/books/punishmentgui---litebansgui-advancedbangui
#Ideas/Feedback: https://feedback.bghddevelopment.com/
#=======================================================
#Permssion: punishmentgui.update
Update:
  Enabled: true
#Enables if there is a message on-join when the plugin is outdated.
#=======================================================
CheckForUpdates:
  Enabled: true
#Enables a message in console if the plugin is outdated.
#=======================================================
SilentStart:
  Enabled: false
#Removes startup messages.
#=======================================================
#Commands & Permissions:
#/punish (playername) - punish.use
#=======================================================
#Main Command Messages:
Prefix: "&8ErrBan &7>> "
NoMessage: "&c¡Invalido! Usa /punish (jugador)!"
NoPermission: "&c(!) ¡No tienes permiso para usar este comandos!"
NoPlayer: "¡Solo un jugador puede ejecutar este comando!"
NameLength: "&c¡Este nombre es muy largo! ¡Solo puedes poner 16 carecteres!"
#=======================================================
InventoryName: "&c&lBANEOS / AVISOS"
